# Generated by Django 6.0.3 on 2026-03-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.ForeignKey(blank=True, help_text='If null, product is available to all vendor schools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='schools.school'),
        ),
    ]
