# Generated by Django 4.2.29 on 2026-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_care_instructions_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='school_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='School commission % on this product (overrides platform default)', max_digits=5),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='school_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variant-level school commission % (overrides product level if set)', max_digits=5, null=True),
        ),
    ]
