# Generated by Django 4.2.29 on 2026-04-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('schools', '0004_school_school_user'),
        ('orders', '0005_order_distributed_at_order_distributed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat (₹ off)'), ('percent', 'Percentage (% off)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percent coupons', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schools', models.ManyToManyField(blank=True, related_name='coupons', to='schools.school')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='vendors.vendor')),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
