# Generated by Django 4.2.29 on 2026-04-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending Clearance'), ('cleared', 'Cleared for Payout'), ('settled', 'Settled / Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
