# Generated by Django 4.2.29 on 2026-05-02 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_school_commission_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_order_payout_status_order_platform_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='distribution_status',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_at_school', 'Pay at School'), ('online', 'Online')], default='pay_at_school', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='exchange_inventory',
            field=models.ForeignKey(blank=True, help_text='New variant requested in exchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='products.productinventory'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='new_item_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='new_item_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='raised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='raised_by_school',
            field=models.BooleanField(default=False, help_text='True if raised by school on behalf of student'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', '01 Placed'), ('awaiting_confirmation', '02 Awaiting Confirmation'), ('confirmed', '03 Confirmed'), ('processing', '04 Processing'), ('shipped', '05 Shipped'), ('delivered', '06 Delivered'), ('distributed', '07 Distributed'), ('cancelled', '08 Cancelled'), ('refunded', '09 Refunded')], default='placed', max_length=25),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(choices=[('return', 'Return (Refund)'), ('exchange', 'Exchange (Size/Color)')], default='exchange', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('vendor_approved', 'Vendor Approved'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Item Picked Up'), ('new_item_shipped', 'New Item Shipped'), ('new_item_delivered', 'New Item Delivered to School'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
