# Generated by Django 4.2.29 on 2026-05-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_cart_student_profile_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', '01 Awaiting Confirmation'), ('processing', '02 Processing'), ('shipped', '03 Shipped'), ('delivered', '04 Delivered'), ('distributed', '05 Distributed'), ('cancelled', '06 Cancelled'), ('refunded', '07 Refunded')], default='awaiting_confirmation', max_length=25),
        ),
    ]
