# Generated by Django 4.2.29 on 2026-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='verification/id_cards/'),
        ),
    ]
