# Generated by Django 4.2.29 on 2026-04-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_id_card_to_verification_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_card_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/id_cards/'),
        ),
    ]
