# Generated by Django 4.2.29 on 2026-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('school', 'roll_number'), name='unique_school_roll_number_nonempty'),
        ),
    ]
