# Generated by Django 4.2.29 on 2026-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_school_roll_number_nonempty',
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('school', 'class_name', 'section', 'roll_number'), name='unique_school_class_section_roll_number'),
        ),
    ]
