# Generated by Django 4.2.29 on 2026-05-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_fix_roll_number_unique_per_class_section'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_school_class_section_roll_number',
        ),
    ]
