# Generated by Django 4.2.29 on 2026-04-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='custom_body_end',
            field=models.TextField(blank=True, help_text='Injected before closing </body> tag'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='custom_head',
            field=models.TextField(blank=True, help_text='Injected before closing </head> tag'),
        ),
    ]
