# Generated by Django 4.2.29 on 2026-04-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_can_manage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
