# Generated by Django 4.2.29 on 2026-05-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_orders',
            field=models.BooleanField(default=True),
        ),
    ]
