# Generated by Django 4.2.29 on 2026-05-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_can_manage_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
