# Generated by Django 4.2.29 on 2026-04-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_contact_email_vendor_contact_phone'),
        ('schools', '0004_school_school_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='vendors.vendor'),
        ),
    ]
