# Generated by Django 4.2.29 on 2026-04-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_contact_email_vendor_contact_phone'),
        ('schools', '0005_alter_school_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_vendor_requests', to='vendors.vendor')),
                ('old_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_vendor_requests', to='vendors.vendor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_change_requests', to='schools.school')),
            ],
            options={
                'db_table': 'vendor_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
